spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reto
    password: "1379"
    username: "root"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect